name: validate
on: [push]
jobs:
  # run-tflint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - uses: actions/cache@v2
  #     name: Cache plugin dir
  #     with:
  #       path: ~/.tflint.d/plugins
  #       key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

  #   - uses: terraform-linters/setup-tflint@v1
  #     name: Setup TFLint
  #     with:
  #       tflint_version: v0.32.1

  #   - uses: hashicorp/setup-terraform@v1
  #     name: Setup Terraform
  #     with:
  #       terraform_version: 0.13.7

  #   - name: terraform-init
  #     run: terraform init

  #   - name: Show version
  #     run: tflint --version

  #   - name: Init TFLint
  #     run: tflint --init

  #   - name: Run TFLint
  #     run: tflint -f compact

name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec_commenter:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec commenter
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}